/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EPCModel: typeof import('./src/components/QIR/EPCModel.vue')['default']
    ExportPdf: typeof import('./src/components/QIR/ExportPdf.vue')['default']
    ExportPdf2: typeof import('./src/components/QIR/ExportPdf2.vue')['default']
    ForemanLogin: typeof import('./src/components/QIR/ForemanLogin.vue')['default']
    Handover: typeof import('./src/components/QIR/Handover.vue')['default']
    Photograph: typeof import('./src/components/QIR/Photograph.vue')['default']
    PhotoWall: typeof import('./src/components/QIR/PhotoWall.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SbHeader: typeof import('./src/components/SbHeader.vue')['default']
    SelectImg: typeof import('./src/components/QIR/SelectImg.vue')['default']
    ShowImage: typeof import('./src/components/QIR/ShowImage.vue')['default']
    ShowPDF: typeof import('./src/components/QIR/ShowPDF.vue')['default']
    SpecialRequest: typeof import('./src/components/QIR/SpecialRequest.vue')['default']
    UpdateIP: typeof import('./src/components/QIR/UpdateIP.vue')['default']
    UpdateQICModel: typeof import('./src/components/QIR/UpdateQICModel.vue')['default']
    UploadImage: typeof import('./src/components/QIR/UploadImage.vue')['default']
    UploadImageHand: typeof import('./src/components/QIR/UploadImageHand.vue')['default']
    UploadImageHand2: typeof import('./src/components/QIR/UploadImageHand2.vue')['default']
    UploadImg: typeof import('./src/components/QIR/UploadImg.vue')['default']
    UploadImg2: typeof import('./src/components/QIR/UploadImg2.vue')['default']
    UploadImgList: typeof import('./src/components/QIR/UploadImgList.vue')['default']
    UploadQICFile: typeof import('./src/components/QIR/UploadQICFile.vue')['default']
  }
}
